version: "3.8"

services:
  db:
    image: mariadb:11.2.2
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3032:3306
    env_file:
      - ./backend/.env
    networks:
      - notes
    volumes:
      - ./db:/var/lib/mysql 
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql 
    command: --init-file /docker-entrypoint-initdb.d/init-db.sql 
  backend:
    image: jihwooon/note-backend:lts
    environment:
      DB_HOST: db
      DB_PORT: 3036
    ports:
      - 3031:3031
    networks:
      - notes
  
  fronted:
    image: jihwooon/note-frontend:lts
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3031
    ports:
      - 3000:3000
    networks:
      - notes 

networks:
  notes: {}
