version: "3.8"

services:
  db:
    image: mariadb:11.2.2
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3032:3306
    networks:
      - notes
    volumes:
      - ./db:/var/lib/mysql
  
  backend:
    image: lts-backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - 3031:3031
    networks:
      - notes

networks:
  notes:
