apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-be-config
  namespace: prgms-notes
data:
  DB_HOST: jihwooon.prgms-fullcycle.com
  DB_USER: prgms
  DB_PASSWD: prgms
  DB_NAME: prgms_notes
  CORS_ALLOWED_ORIGIN: https://jihwooon.prgms-fullcycle.com

---

apiVersion: apps/v1 
kind: Deployment

metadata:
  name: notes-be 
  namespace: prgms-notes
spec: 
  replicas: 1 
  selector:
    matchLabels: 
      run: notes-be
  template: 
    metadata:
      labels:
        run: notes-be
    spec:
      containers:
      - name: notes-backend
        image: 180993267331.dkr.ecr.ap-northeast-2.amazonaws.com/jihwooon-be:latest
        imagePullPolicy: Always 
        envFrom:
        - configMapRef:
            name: notes-be-config

---

apiVersion: v1 
kind: Service

metadata: 
  name: notes-be 
  labels:
    run: notes-be 
  namespace: prgms-notes

spec:
  type: NodePort 
  selector:
    run: notes-be 
  ports:
  - port: 3031
    targetPort: 3031 
    nodePort: 30031
